### ISSUE TITLE
Stream Creation failed

### ISSUE THREAD

**Issue by rahvis** [gersteinlab/SAMChain#3]
[root@user-10 SAMChain]# python --version
**Python 2.7.5**

[root@user-10 SAMChain]# **/usr/local/bin/multichain-cli -version**
MultiChain 1.0.9 RPC client

[root@user-10 SAMChain]# uname -a
Linux user-10.domain.com 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@user-10 SAMChain]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release **7.5 (Maipo)**

[root@user-10 SAMChain]# **python buildChain.py a_out.bam -cn cn1 -dr bc/**
--CHAIN CREATION--
Created chain

MultiChain 1.0.9 Daemon (latest protocol 10012)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
multichaind cn1@10.230.161.185:6717

This host has multiple IP addresses, so from some networks:
multichaind cn1@192.168.122.1:6717

Listening for API requests on port 6716 (local only - see rpcallowip setting)

Node ready.

--STREAM CREATION--
**Traceback (most recent call last):
  File "buildChain.py", line 333, in <module>
    main()
  File "buildChain.py", line 316, in main
    num_streams = createStreams(args.chainName, 23, args.lengthChromosome, args.lengthBin, args.lengthRead, args.multichainLoc, args.datadir)
  File "buildChain.py", line 103, in createStreams
    publishToStream(chainName, datadir, "metaData", ("chainInfo",), multichainLoc, chainData)
  File "buildChain.py", line 81, in publishToStream
    dummy = subprocess.check_output(publishCommand, stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['multichain-cli', 'cn1', '-datadir=bc/', 'publish', 'metaData', '["chainInfo"]', '{"json":{"binLength":10000000, "readLength":100, "numBins":25}}']' returned non-zero exit status 8**

**Creating a .bam file**
import pysam
header = { 'HD': {'VN': '1.0'},
            'SQ': [{'LN': 1575, 'SN': 'chr1'},
                   {'LN': 1584, 'SN': 'chr2'}] }

tmpfilename = 'a_out.bam'

with pysam.AlignmentFile(tmpfilename, "wb", header=header) as outf:
    a = pysam.AlignedSegment()
    a.query_name = "read_28833_29006_6945"
    a.query_sequence="AGCTTAGCTAGCTACCTATATCTTGGTCTTGGCCG"
    a.flag = 99
    a.reference_id = 0
    a.reference_start = 32
    a.mapping_quality = 20
    a.cigar = ((0,10), (2,1), (0,25))
    a.next_reference_id = 0
    a.next_reference_start=199
    a.template_length=167
    a.query_qualities = pysam.qualitystring_to_array("<<<<<<<<<<<<<<<<<<<<<:<9/,&,22;;<<<")
    a.tags = (("NM", 1),
              ("RG", "L1"))
    outf.write(a_out.bam)

**Tried on** http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/**wgEncodeUwRepliSeqGm12801G1bAlnRep1.bam**

[root@user-10 SAMChain]# python buildChain.py wgEncodeUwRepliSeqGm12801G1bAlnRep1.bam -cn cn2 -dr bc/
--CHAIN CREATION--
Created chain

MultiChain 1.0.9 Daemon (latest protocol 10012)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
multichaind cn2@10.230.161.185:2775

This host has multiple IP addresses, so from some networks:
multichaind cn2@192.168.122.1:2775

Listening for API requests on port 2774 (local only - see rpcallowip setting)

Node ready.

--STREAM CREATION--
Traceback (most recent call last):
  File "buildChain.py", line 383, in <module>
    main()
  File "buildChain.py", line 364, in main
    args.lengthBin, args.lengthRead, args.multichainLoc, args.datadir)
  File "buildChain.py", line 127, in createStreams
    ("chainInfo",), multichainLoc, chainData)
  File "buildChain.py", line 98, in publishToStream
    dummy = subprocess.check_output(publishCommand, stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['multichain-cli', 'cn2', '-datadir=bc/', 'publish', 'metaData', '["chainInfo"]', '{"json":{"binLength":10000000, "readLength":100, "numBins":25}}']' returned non-zero exit status 8

**Comment by rahvis** [comment]
Comment line #98 in **buildChain.py**
#dummy = subprocess.check_output(publishCommand, stderr=subprocess.STDOUT)

Requirement: **pip install psutil**

[root@user-10 SAMChain]# python buildChain.py a_out.bam -cn cn8 -dr bc
--CHAIN CREATION--
Created chain

MultiChain 1.0.9 Daemon (latest protocol 10012)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
multichaind cn8@10.230.161.185:7319

This host has multiple IP addresses, so from some networks:
multichaind cn8@192.168.122.1:7319

Listening for API requests on port 7318 (local only - see rpcallowip setting)

Node ready.

--STREAM CREATION--
--PREPROCESSING--
--INSERTING DATA--
Chain construction complete! Chain name: cn8


 Total memory in bytes:


14921728
